services:
  # postgres - Temporarily commented out
  # postgres:
  #   image: postgres:18.1-alpine
  #   ports:
  #     - 5432:5432
  #   env_file:
  #     - .env
  #     - .env.development
  #   environment:
  #     POSTGRES_DB: ${DB_NAME:?err}
  #     POSTGRES_USER: ${DB_USER:?err}
  #     POSTGRES_PASSWORD: ${DB_PASS:?err}
